### username "numberTwo" creates article:
POST http://localhost:3000/articles
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJOdW1iZXJUd28iLCJlbWFpbCI6Im51bWJlclR3b0BnbWFpbC5jb20iLCJpYXQiOjE2NzY4NDIxMzl9.qfEcut2wy6zIDZZiQGhW7rAq9eayhQDVKEPFRScB2og

{
  "article": {
    "title": "How to create a water buffalo",
    "description": "numberTwo explains how to...",
    "body": "lorem X 100",
    "tagList": ["js", "nodejs"]
  }
}

### username "numberTwo" creates article:
POST http://localhost:3000/articles
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJOdW1iZXJUd28iLCJlbWFpbCI6Im51bWJlclR3b0BnbWFpbC5jb20iLCJpYXQiOjE2NzY4NDIxMzl9.qfEcut2wy6zIDZZiQGhW7rAq9eayhQDVKEPFRScB2og

{
  "article": {
    "title": "Another article by numberTwo",
    "description": "numberTwo explains how to...",
    "body": "lorem X 200",
    "tagList": ["java"]
  }
}

### username "numberTwo" creates article:
POST http://localhost:3000/articles
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJOdW1iZXJUd28iLCJlbWFpbCI6Im51bWJlclR3b0BnbWFpbC5jb20iLCJpYXQiOjE2NzY4NDIxMzl9.qfEcut2wy6zIDZZiQGhW7rAq9eayhQDVKEPFRScB2og

{
  "article": {
    "title": "Latest article by numberTwo",
    "description": "numberTwo explains how to...",
    "body": "lorem X 300",
    "tagList": ["js", "reactjs"]
  }
}

### Find article by slug
GET http://localhost:3000/articles/first-article


### Find All articles made by current user
GET http://localhost:3000/articles
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJUZXN0aW5nVXNlciIsImVtYWlsIjoicXdlcnR5QGdtYWlsLmNvbSIsImlhdCI6MTY3NjgyNDk3Mn0.ySiXkoP8Wx8GbYWna5-6wn0B0TzDq_GBsFhUtlWP1lw

### Find All with pagination query
GET http://localhost:3000/articles?limit=2&offset=0
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJUZXN0aW5nVXNlciIsImVtYWlsIjoicXdlcnR5QGdtYWlsLmNvbSIsImlhdCI6MTY3NjgyNDk3Mn0.ySiXkoP8Wx8GbYWna5-6wn0B0TzDq_GBsFhUtlWP1lw

### Find All with certain tag as a query
GET http://localhost:3000/articles?tag=Java
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJUZXN0ZXIiLCJlbWFpbCI6InRlc3RAdGVzdGluZy5jb20iLCJpYXQiOjE2NzYzMjgyMDN9.xqyPmM20VkxQQbOnLOGgGVKkVrwvOP5hQCYnjXEZnC8

### Find articles made by specified author
GET http://localhost:3000/articles?author=BananaMan
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJCYW5hbmFNYW4iLCJlbWFpbCI6Im5ld0VtYWlsRm9ySm9ubnlAdGVzdC5jb20iLCJpYXQiOjE2NzYzODQyOTR9.GwaReNGQG5aBSdKTwYvGyvSo-etBlWWOlobn5A-v9eY

### Find articles by user and tag
GET http://localhost:3000/articles?author=Tester&tag=Java
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJCYW5hbmFNYW4iLCJlbWFpbCI6Im5ld0VtYWlsRm9ySm9ubnlAdGVzdC5jb20iLCJpYXQiOjE2NzYzODQyOTR9.GwaReNGQG5aBSdKTwYvGyvSo-etBlWWOlobn5A-v9eY

### Find articles by user and tag, no auth
GET http://localhost:3000/articles?author=Tester&tag=Java

### Find favorited articles
GET http://localhost:3000/articles?favorited=BananaMan

### Find favorited with auth
GET http://localhost:3000/articles?favorited=BananaMan
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJCYW5hbmFNYW4iLCJlbWFpbCI6Im5ld0VtYWlsRm9ySm9ubnlAdGVzdC5jb20iLCJpYXQiOjE2NzYzODQyOTR9.GwaReNGQG5aBSdKTwYvGyvSo-etBlWWOlobn5A-v9eY

### add article to favorites:
POST http://localhost:3000/articles/new-title-testing-stuffs-9b343e/favorite
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJCYW5hbmFNYW4iLCJlbWFpbCI6Im5ld0VtYWlsRm9ySm9ubnlAdGVzdC5jb20iLCJpYXQiOjE2NzYzODQyOTR9.GwaReNGQG5aBSdKTwYvGyvSo-etBlWWOlobn5A-v9eY

### remove article from favorites:
DELETE http://localhost:3000/articles/new-title-testing-stuffs-9b343e/favorite
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJCYW5hbmFNYW4iLCJlbWFpbCI6Im5ld0VtYWlsRm9ySm9ubnlAdGVzdC5jb20iLCJpYXQiOjE2NzYzODQyOTR9.GwaReNGQG5aBSdKTwYvGyvSo-etBlWWOlobn5A-v9eY

### Feed
GET http://localhost:3000/articles/feed/
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJOdW1iZXJUd28iLCJlbWFpbCI6Im51bWJlclR3b0BnbWFpbC5jb20iLCJpYXQiOjE2NzY4NDEyNTR9.QiVfGAGZuoEkOSHZxut10nKY2vHm5AFIlxDKfGHkmHw

### Feed
GET http://localhost:3000/articles/feed
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJUZXN0aW5nVXNlciIsImVtYWlsIjoicXdlcnR5QGdtYWlsLmNvbSIsImlhdCI6MTY3Njg0MTgzMn0.rvowdEJYXep0zNxCXZAnLfQGB6g0gYPil8h_OAQ2XFw

### Feed with limit
GET http://localhost:3000/articles/feed?limit=1
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJUZXN0aW5nVXNlciIsImVtYWlsIjoicXdlcnR5QGdtYWlsLmNvbSIsImlhdCI6MTY3Njg0MTgzMn0.rvowdEJYXep0zNxCXZAnLfQGB6g0gYPil8h_OAQ2XFw