### Create user
POST  http://localhost:3000/users
Content-Type: application/json

{
  "user": {
    "username": "BoyHarsher",
    "email": "Gimme@AReason.com",
    "password": "reddyB"
  }
}

### email is taken
POST  http://localhost:3000/users
Content-Type: application/json

{
  "user": {
    "username": "Bobby",
    "email": "jonny@test.com",
    "password": "Bobby"
  }
}

### username is taken
POST  http://localhost:3000/users
Content-Type: application/json

{
  "user": {
    "username": "Jonny",
    "email": "Bobby@test.com",
    "password": "Bobby"
  }
}


### Invalid
POST  http://localhost:3000/users
Content-Type: application/json

{
  "user": {
    "email": "jonny@test.com",
    "password": "jonnyB"
  }
}

### Login
POST  http://localhost:3000/users/login
Content-Type: application/json

{  
  "user": {
    "email": "jonny@test.com",
    "password": "jonnyB"
  }
}

### Login with incorrect password
POST  http://localhost:3000/users/login
Content-Type: application/json

{  
  "user": {
    "email": "jonny@test.com",
    "password": "babaganush"
  }
}

### Get current User:
GET http://localhost:3000/user

### Get current User with auth token
GET http://localhost:3000/user
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJKb25ueSIsImVtYWlsIjoiam9ubnlAdGVzdC5jb20iLCJpYXQiOjE2NzYyODMyMDR9.GBqxmLYFDOMNxWxC2pgGuC3kmHU8DgwkHjOF777cbu4